import React, { useState, useReducer } from "react";
import { makeStyles } from "@material-ui/core/styles";

import {
  Grid,
  Button,
  Hidden,
  Modal,
  Fade,
} from "@material-ui/core";

import reducer from "../../common/reducer.js"
import Carousel from "../../components/Carousel.js"
import BetSlip from "../../components/BetSlip.js"
import BookMaker from "../../components/BookMaker.js"

import styles from "../../assets/js/pages/Home/homePageStyle.js";

const useStyles = makeStyles(styles);

export default function Home(props) {
  const classes = useStyles();
  const [state, dispatch] = useReducer(reducer, initialState)
  const { betGames, slipsCounter } = state;
  const [modalOpen, setModalOpen] = useState(false);

  const handleOpen = () => {
    setModalOpen(true);
  };

  const handleClose = () => {
    setModalOpen(false);
  };

  return (
    <div className={classes.container}>
      <Carousel />

      <Grid container justify="center">
        <Button variant="outlined" className={classes.btnSignIn}>
          Sign up in one click!
        </Button>
      </Grid>

      <Grid container>
        <BookMaker
          dispatch={dispatch}
          live={false}
          betGames={betGames}
        />
        <Hidden smDown>
          <div className={classes.betSlip + " col-lg-4 offset-lg-0 col-xl-3 d-none d-lg-block"}>
            <BetSlip dispatch={dispatch} betGames={betGames} slipsCounter={slipsCounter} />
          </div>
        </Hidden>
      </Grid>
      <Hidden mdUp>
        <Grid container justify="center">
          {
            slipsCounter !== 0
              ?
              <>
                <Button
                  variant="outlined"
                  className={classes.btnBetSlip}
                  onClick={handleOpen}
                >
                  bet slip
                <span className={classes.slipsCounter}>{slipsCounter}</span>
                </Button>
                <Modal
                  open={modalOpen}
                  onClose={handleClose}
                  className={classes.modal}
                  aria-labelledby="bet-slip-title"
                  aria-describedby="bet-slip-description"
                >
                  <Fade in={modalOpen}>
                    <div className={classes.betSlip}>
                      <BetSlip dispatch={dispatch} betGames={betGames} slipsCounter={slipsCounter} />
                    </div>
                  </Fade >
                </Modal>
              </>
              : <></>
          }
        </Grid>
      </Hidden>
    </div>
  );
}

const initialState = {
  slipsCounter: 0,
  betGames: [
    {
      index: 0,
      sport: "Soccer",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 1,
      sport: "Soccer",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 2,
      sport: "Soccer",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 3,
      sport: "Soccer",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 4,
      sport: "Soccer",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 5,
      sport: "Soccer",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 6,
      sport: "Soccer",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 7,
      sport: "Soccer",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 8,
      sport: "Soccer",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 9,
      sport: "BasketBall",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 10,
      sport: "BasketBall",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 11,
      sport: "BasketBall",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 12,
      sport: "BasketBall",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 13,
      sport: "BasketBall",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 14,
      sport: "BasketBall",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 15,
      sport: "BasketBall",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 16,
      sport: "BasketBall",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 17,
      sport: "BasketBall",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 18,
      sport: "Tennis",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 19,
      sport: "Tennis",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 20,
      sport: "Tennis",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 21,
      sport: "Tennis",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 22,
      sport: "Tennis",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 23,
      sport: "Tennis",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 24,
      sport: "Tennis",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 25,
      sport: "Tennis",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 26,
      sport: "Tennis",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 27,
      sport: "VolleyBall",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 28,
      sport: "VolleyBall",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 29,
      sport: "VolleyBall",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 30,
      sport: "VolleyBall",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 31,
      sport: "VolleyBall",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 32,
      sport: "VolleyBall",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 33,
      sport: "VolleyBall",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 34,
      sport: "VolleyBall",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 35,
      sport: "VolleyBall",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 36,
      sport: "Rugby",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 37,
      sport: "Rugby",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 38,
      sport: "Rugby",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 39,
      sport: "Rugby",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 40,
      sport: "Rugby",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 41,
      sport: "Rugby",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 42,
      sport: "Rugby",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 43,
      sport: "Rugby",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 44,
      sport: "Rugby",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 45,
      sport: "Hockey",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 46,
      sport: "Hockey",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 47,
      sport: "Hockey",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 48,
      sport: "Hockey",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 49,
      sport: "Hockey",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 50,
      sport: "Hockey",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 51,
      sport: "Hockey",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 52,
      sport: "Hockey",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 53,
      sport: "Hockey",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 54,
      sport: "Esports",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 55,
      sport: "Esports",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 56,
      sport: "Esports",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 57,
      sport: "Esports",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 58,
      sport: "Esports",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 59,
      sport: "Esports",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 60,
      sport: "Esports",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 61,
      sport: "Esports",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 62,
      sport: "Esports",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 63,
      sport: "Chess",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },  
    {
      index: 64,
      sport: "Chess",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 65,
      sport: "Chess",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 66,
      sport: "Chess",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 67,
      sport: "Chess",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 68,
      sport: "Chess",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 69,
      sport: "Chess",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 70,
      sport: "Chess",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },
    {
      index: 71,
      sport: "Chess",
      time: "9:30",
      date: "11 Feb",
      hostTeamImg: require("../../assets/img/FC_Chelsea_Logo.svg.png"),
      guestTeamImg: require("../../assets/img/Tottenham_Hotspur.svg"),
      hostTeamName: "Chelsea",
      guestTeamName: "Tottenham Hotspur",
      round: "Second Half",
      livingTime: "19m : 10s",
      hostScore: "0",
      guestScore: "4",
      bet1X: { status: false, type: "bet1X", value: "3.25" },
      betX: { status: false, type: "betX", value: "5.00" },
      bet2X: { status: false, type: "bet2X", value: "8.00" },
      handicap_0: { status: false, type: "handicap_0", value: "2.851" },
      handicap_1: { status: false, type: "handicap_1", value: "1.456" },
      over: { status: false, type: "over", value: "2.851" },
      under: { status: false, type: "under", value: "1.456" },
    },      
  ],
};

